name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hkusu/review-assign-action@v1
        with:
          reviewers: diomonogatari
